name: comp_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  get: ^4.6.6
  intl: ^0.20.1
  dropdown_button2: ^2.3.9
  json_annotation: ^4.9.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  json_serializable: ^6.9.0
  build_runner: ^2.4.14

  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true




